AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud

#-------------------------------------
#   Meta Data
#-------------------------------------
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Envrionment
        Parameters:
          - LabName
      -
        Label:
          default: Network Configuration
        Parameters:
          - VPCCidr
          - PublicSubnet01Cidr
      -
        Label:
          default: EC2 Configuration
        Parameters:
          - Ec2ImageId
          - KeyPair

#-------------------------------------
#   Parameters
#-------------------------------------
Parameters:
  LabName:
    Type: String
    AllowedValues:
      - ie3a
      - ie3b
      - sk3a
      - sk3b
  VPCCidr:
    Type: String
    Default: "10.2.0.0/16"
  PublicSubnet01Cidr:
    Type: String
    Default: "10.2.1.0/24"
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select KeyPair Name.
  Ec2ImageId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'

#-------------------------------------
#   Resources
#-------------------------------------
Resources:

#-------------------------------------
#   VPC
#-------------------------------------
  Vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: !Ref VPCCidr
      Tags:
        - Key: Name
          Value: !Sub "${LabName}_aurora_vpc"
#-------------------------------------
#   Internet Gateway
#-------------------------------------
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: 'Name'
        Value: !Sub "${LabName}_aurora_igw"
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref Vpc
      InternetGatewayId: !Ref InternetGateway

#-------------------------------------
#   Subnet
#-------------------------------------
  Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      CidrBlock: !Ref  PublicSubnet01Cidr
      MapPublicIpOnLaunch: true
      Tags:
        - Key: 'Name'
          Value: !Sub '${LabName}_web_sub'
      VpcId: !Ref Vpc

#-------------------------------------
#   Route table
#-------------------------------------
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: !Sub '${LabName}_aurora_rt'
      VpcId: !Ref Vpc
  Route:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

#-------------------------------------
#   EC2 Instance
#-------------------------------------
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref Ec2ImageId
      InstanceType: "t3.micro"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !Ref Subnet
          GroupSet:
            - !Ref IngressSecurityGroup
      Tags:
        - Key: 'Name'
          Value: !Sub "${LabName}_aurora_websv"
      KeyName: !Ref KeyPair
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum -y install httpd
          systemctl enable httpd
          yum -y install php php-fpm php-mysqli php-devel php-json
          systemctl start httpd
          echo "<?php phpinfo(); ?>" > /var/www/html/test.php 

#-------------------------------------
#   Security Group
#-------------------------------------    
  IngressSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "eccSecurityGroup"
      VpcId: !Ref Vpc
      Tags:
        - Key: 'Name'
          Value: !Sub '${LabName}-auroa-websg'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0