AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud

Parameters:
  #キーペア
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select KeyPair Name.
  #AMI
  AMI:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2' 
  #InstanceAZ:
  #  Type: AWS::EC2::AvailabilityZone::Name
  #  Description: Select AvailabilityZone Name.

 
Resources:
  #VPC
  eccVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.1.0.0/16'
      Tags:
        - Key: 'Name'
          Value: 'ie3a_vpc'
  #subnet(public_a)
  eccSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      CidrBlock: '10.1.10.0/24'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: 'Name'
          Value: 'ie3a_ec2_docker'
      VpcId: !Ref eccVpc

  #InternetGateway
  eccInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: 'Name'
        Value: 'ie3a-gw'
  
  #EIP  
  eccEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref eccVpc

  #NATGateway
  eccNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId : !GetAtt eccEIP.AllocationId
      SubnetId: !Ref eccSubnet
      Tags:
      - Key: Name
        Value: ie3a_nat_gw

  #VPCとInternetGatewayの間れ付け
  eccAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref eccVpc
      InternetGatewayId: !Ref eccInternetGateway
  
  #RouteTable
  eccRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'ie3a_rt'
      VpcId: !Ref eccVpc

  #RouteTableの作成
  eccRoute:
    Type: AWS::EC2::Route
    DependsOn: eccInternetGateway
    Properties:
      RouteTableId: !Ref eccRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref eccInternetGateway
  
  #subnetとRouteTableの関連付け
  eccSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref eccSubnet
      RouteTableId: !Ref eccRouteTable
  
  #EC2(ie3a_ec2_docker)
  eccEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: "t2.micro"
      SubnetId: !Ref eccSubnet
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: 8
      Tags:
        - Key: 'Name'
          Value: 'ie3a_ec2_docker'
      SecurityGroupIds:
        - !Ref eccSecurityGroup
      KeyName: !Ref KeyPair

  #SecurityGroup   
  eccSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "eccSecurityGroup"
      VpcId: !Ref eccVpc
      Tags:
        - Key: 'Name'
          Value: 'ie3a-sg'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8080'
        ToPort: '8080'
        CidrIp: 0.0.0.0/0