AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud

Parameters:
  #キーペア
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select KeyPair Name.
  #AMI
  AMI:
    # Type: 'AWS::SSM::Parameter::Value<String>'
    # Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2' 
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64'
  #InstanceAZ:
  #  Type: AWS::EC2::AvailabilityZone::Name
  #  Description: Select AvailabilityZone Name.

Resources:
  #VPC
  eccVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.1.0.0/16'
      Tags:
        - Key: 'Name'
          Value: 'sk3a_vpc'
  #subnet(public_a)
  eccSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 0
          - Fn::GetAZs: ""
      CidrBlock: '10.1.10.0/24'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: 'Name'
          Value: 'sk3a_public_a'
      VpcId: !Ref eccVpc

  #subnet(private_b)
  eccSubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: 
        Fn::Select: 
          - 1
          - Fn::GetAZs: ""
      CidrBlock: '10.1.11.0/24'
      Tags:
        - Key: 'Name'
          Value: 'sk3a_private_b'
      VpcId: !Ref eccVpc

  #InternetGateway
  eccInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: 'Name'
        Value: 'sk3a-gw'
  
  #EIP  
  eccEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref eccVpc

  #NATGateway
  eccNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId : !GetAtt eccEIP.AllocationId
      SubnetId: !Ref eccSubnet
      Tags:
      - Key: Name
        Value: sk3a_nat_gw

  #VPCとInternetGatewayの間れ付け
  eccAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref eccVpc
      InternetGatewayId: !Ref eccInternetGateway
  
  #RouteTable(public_a)
  eccRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'sk3a_rt'
      VpcId: !Ref eccVpc

  #RouteTable(private_b)
  eccRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      Tags:
        - Key: 'Name'
          Value: 'sk3a_private_rt'
      VpcId: !Ref eccVpc  

  #RouteTable(public_a)の作成
  eccRoute:
    Type: AWS::EC2::Route
    DependsOn: eccInternetGateway
    Properties:
      RouteTableId: !Ref eccRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref eccInternetGateway
  
  #RouteTable(private_b)の作成
  eccRoute2:
    Type: AWS::EC2::Route
    DependsOn: eccInternetGateway
    Properties:
      RouteTableId: !Ref eccRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref eccNatGateway

  #subnetとRouteTable(public_a)の関連付け
  eccSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref eccSubnet
      RouteTableId: !Ref eccRouteTable
  
  #subnet2とRouteTable(private_b)の関連付け
  eccSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref eccSubnet2
      RouteTableId: !Ref eccRouteTable2

  #EC2(public_a)
  eccEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: "t2.micro"
      SubnetId: !Ref eccSubnet
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: 8
      Tags:
        - Key: 'Name'
          Value: 'sk3a_public_a'
      SecurityGroupIds:
        - !Ref eccSecurityGroup
      KeyName: !Ref KeyPair

  #EC2(private_b)
  eccEC2Instance2:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMI
      InstanceType: "t2.micro"
      SubnetId: !Ref eccSubnet2
      BlockDeviceMappings:
        - DeviceName: '/dev/xvda'
          Ebs:
            VolumeType: 'gp2'
            VolumeSize: 8
      Tags:
        - Key: 'Name'
          Value: 'sk3a_private_b'
      SecurityGroupIds:
        - !Ref eccSecurityGroup2
      KeyName: !Ref KeyPair

  #SecurityGroup(public_a)    
  eccSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "eccSecurityGroup"
      VpcId: !Ref eccVpc
      Tags:
        - Key: 'Name'
          Value: 'sk3a-sg'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
  
  #SecurityGroup(private_b)
  eccSecurityGroup2:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "eccSecurityGroup2"
      VpcId: !Ref eccVpc
      Tags:
        - Key: 'Name'
          Value: 'sk3a-sg2'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 10.1.0.0/16
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 10.1.0.0/16
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 10.1.0.0/16
      - IpProtocol: icmp
        FromPort: '8'
        ToPort: '-1'
        CidrIp: 10.1.0.0/16